project_id = "mfayoazhicnsvgqflfmh"

[functions.create-payment-intent]
verify_jwt = true

[functions.previsao-manutencao]
verify_jwt = true

[functions.processar-manual]
verify_jwt = true

[functions.buscar-manual]
verify_jwt = true
